### ISSUE TITLE
Add a collector that collects and stores the Container Stats from the Docker Stats API

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/collectors#1]
The required functionalities are:
1. it must work from inside a container;
2. it must collect the Stats of a list of containers identified by names and provided through an Environment variables. The containers's name are separated by ":";
3. it must store the stats on a tmp file local to the container;
4. it must define APIs to decide when to start and stop the data collection;
5. as for the other collectors: it must define APIs to zip the data and store them on a remote S3 compatible datastore;
6. it must work with the less impact as possible on the monitored container performance.

Notes about CPU usage:
- Compute the percentage usage given the number of core assigned to a container, not according to the host
- cpushares: can be a relative weight to other containers
- total_usage: CPU percentage is not feasible because Docker enables many options to share the CPU with other containers. We use the total_usage instead.

Some useful references:
1. Powerful go-dockerclient and Stats API: https://godoc.org/github.com/fsouza/go-dockerclient#Client.Stats
2. A test case that show how to use the API using the client at point 1: https://github.com/fsouza/go-dockerclient/blob/34eaaf52874d8ce5d57be011a4852eb83d950125/container_test.go#L1630
3. Docker Stats APIs: https://docs.docker.com/reference/api/docker_remote_api_v1.20/#get-container-stats-based-on-resource-usage

**Comment by VincenzoFerme** [comment]
@Cerfoglg what it is still missing in your #10 pull request?

**Comment by Cerfoglg** [comment]
Still needs to properly connect to the docker socket rather than using the adress with credentials. We have seen together that it wasn't working right, not even on the servers, so it may need some closer look.

**Comment by VincenzoFerme** [comment]
@Cerfoglg see https://github.com/benchflow/monitors/issues/1#issuecomment-161034530

**Comment by Cerfoglg** [comment]
@VincenzoFerme This issue needs closing, it's been solved a while back
