### ISSUE TITLE
Improve Stats Collector by better handling the stop of the collection

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/collectors#11]
Remove the shared variable "collecting" that handles the stop of the collection, and try to see if it possible to directly use the API to understand when there are no more data.

Useful reference: http://adampresley.com/2015/02/16/waiting-for-goroutines-to-finish-running-before-exiting.html

**Comment by Cerfoglg** [comment]
This can also be closed now, since issue #23 is what's left for the collection stopping

**Comment by VincenzoFerme** [comment]
Closed by #20
