### ISSUE TITLE
Make all collectors use gzip

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/collectors#19]
For all collectors, when zipping a file use gzip for compression. 

By using gzip we remove the need to use external zipping methods, as gzip is present on all linux installations. In addition, gzip compressed files can be used directly by Spark when creating a context if opened directly, and even without it Python has a gzip package as part of the default installation (meaning we also don't have to import any extra python modules for handling compressed data).

Gzip also offers a good compress ratio at a very good speed, which makes it a good choice for the database dumps we are storing on Minio (CSV format).

**Comment by VincenzoFerme** [comment]
Closed by #20
