### ISSUE TITLE
Abstract common collectors functionality in a library

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/collectors#21]

**Comment by Cerfoglg** [comment]
How do you want me to reorganise the collector repository to do this? I want to have the functions for zipping and storing on Minio as common functions to all collectors to start.

**Comment by VincenzoFerme** [comment]
@Cerfoglg You should organise the common code in well defined libraries, as indicated on the official reference: https://golang.org/doc/code.html#Organization

**Comment by VincenzoFerme** [comment]
Fixed by #27
