### ISSUE TITLE
Develop a solution for Minio key hashing

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/collectors#25]
In the format we use for the Minio keys, we append a hash to the key to speed up the lookup when accessing Minio. We require a way to generate the hash for a given key, that can be accessed regardless of implemented language for our components.

The convenient solution is to develop an additional golang microservice we can query to generate the hash of a given key. This way we have a single microservice to handle that, meaning we won't need to implement hashing for other languages, and changing the hash function can be done once in a single location.

In addition, select a hash function to use. Some good ideas to consider here: http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html

**Comment by VincenzoFerme** [comment]
@Cerfoglg you should consider the following, when deciding between a microservice or a library implemented in different languages:
- General description of the PROs and CONS between microservices and shared libraries: http://www.infoq.com/news/2014/09/microservices-shared-libraries
- Details: http://blog.cleancoder.com/uncle-bob/2014/09/19/MicroServicesAndJars.html
- Details: http://www.giorgiosironi.com/2014/09/microservices-are-not-jars.html

At the end you can always use the same hash function, even if you change language.

**Comment by Cerfoglg** [comment]
Well if we are using a popular hashing function like MD5, then all languages are likely to have their own implementation of it somewhere. Golang has a package for it https://golang.org/pkg/crypto/md5/ and Java has MessageDigest like so http://www.asjava.com/core-java/java-md5-example/ . 

If we just let the different languages handle the hashing by themselves, it saves us having another microservice running, as well as having to deal with the hassle of contacting the service to get a hash. Of course, the moment we need to change the hash function for one reason or another, that's where we have to put our hands on the code for every language we have, as opposed to a single microservice. If we don't have too many different languages involved though, and if we use a good hashing function to start, this shouldn't become an issue.

**Comment by VincenzoFerme** [comment]
1. As far as I understood, for this specific use case a popular hashing function is enough, as long as it produces a short hash (e.g., https://aws.amazon.com/blogs/aws/amazon-s3-performance-tips-tricks-seattle-hiring-event/).
2. It is true we might need to change the hash function in the future, and we can not foresee it.

I guess we agree that the best solution in our case is to implement a library in the different languages we develop using this functionality. There would be also another alternatives in which we rely on a tool provided by the underlying operating system, but this would introduce too much overhead.

I created the repo (https://github.com/benchflow/keyname-hash-generator) and opened an issue (benchflow/keyname-hash-generator#1) there to proceed with the implementation of the library.
