### ISSUE TITLE
Implement a Collector That Collects the Container_Properties

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/collectors#31]
Implement a Collector That Collect the Container_Properties as defined in the [BenchFlow database](https://github.com/benchflow/data-transformers/issues/6#issuecomment-160972532).

**Some references:**
- [Inspect a Container](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#inspect-a-container). It might be possible that we can gather all the information about the container, after the benchmark execution is completed, by relying on this API.

**Comment by Cerfoglg** [comment]
@VincenzoFerme I think this then https://godoc.org/github.com/fsouza/go-dockerclient#Client.InspectContainer should do the trick

**Comment by VincenzoFerme** [comment]
@Cerfoglg you just need to cross-check that you can actually get all the information we want to store, through this API.

**Comment by Cerfoglg** [comment]
The API contains method to retrieve all the data via the docker REST api, so inspect containers, and info and version (except the benchflow specific ones).
