### ISSUE TITLE
Add a collector that collects the log of a specified list of Docker containers

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/collectors#4]
The collector is similar to the one that collects Docker Stats (#1), in the sense that it offers similar functionalities but on a different API.

The required functionalities are:
1. it must work from inside a container;
2. it must collect the Logs of a list of containers identified by names and provided through an Environment variables. The containers's name are separated by ":";
3. it must store the stats on a tmp file local to the container;
4. it must enable the timestamps option of the Docker Logs API;
5. it must start the collection immediately after its start;
6. as for the other collectors: it must define APIs to zip the data and store them on a remote S3 compatible datastore;
7. it must work with the less impact as possible on the monitored container performance.

Some useful references:
1. Powerful go-dockerclient and Logs API: https://godoc.org/github.com/fsouza/go-dockerclient#Client.Logs
2. A test case that show how to use the API using the client at point 1: https://github.com/fsouza/go-dockerclient/blob/34eaaf52874d8ce5d57be011a4852eb83d950125/container_test.go#L1153
3. Docker Logs APIs: https://docs.docker.com/reference/api/docker_remote_api_v1.20/#get-container-logs

**Comment by VincenzoFerme** [comment]
@Cerfoglg what it is still missing in your #10 pull request?

**Comment by Cerfoglg** [comment]
Still needs to properly connect to the docker socket rather than using the adress with credentials. We have seen together that it wasn't working right, not even on the servers, so it may need some closer look.

**Comment by VincenzoFerme** [comment]
@Cerfoglg see https://github.com/benchflow/monitors/issues/1#issuecomment-161034530

**Comment by Cerfoglg** [comment]
@VincenzoFerme This issue needs closing, it's been solved a while back
