### ISSUE TITLE
Obtain container ID from stats collector and send it via Kafka

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/collectors#46]
Our current implementation of stats collecting doesn't retrieve or make any use of the container's actual ID when collecting the stats, sending them to Minio and signalling their presence to Kafka. This is an important piece of information, as it is required when the Spark Tasks Sender will eventually execute the stats transformer and store the collected data for the specific container ID.

Modify the current implementation so it:
- Retrieves the linked containers' IDs
- Use container ID to name files on Minio instead of container name
- Sends the container IDs over Kafka. Alter the minio key into a comma separated list of keys, one key per collected stats of a container

---

To indetify the container for which we collected environment statistics, we now rely of the file name of the statistics stored on Minio, that as part of the name has the `container_id`. We then "uniquely" identify a container's stats by grouping the statistics per `experiment_id`, `trial_id` and `container_id`. There can be the (very) unlikely chance that we end up having the same `container_id` for to different containers part of a trial. Then we must use our internally generated `container_properties_id` once we'll also collect the container properties with (probably) a dedicated collector for the scope that should store these data prior to any tranformer needing them can start. 

We should investigate how to guarantee the uniqueness of this association. A possibility can be to store the `container_id` paired (_ separated) with an hash obtained by combining: the container name (that we ensure to generate unique), the host's mac address, the `container_id` itself, the `experiment_id` and the `trial_id`

**Impacted functionalities:**
- Stats Collector
- Spark-Tasks-Sender
- Stats Transformer
- Cassandra schema
- Stats Analysers

**Comment by VincenzoFerme** [comment]
@Cerfoglg are you sure we did not change our mind on it and sending multiple Minio keys?

**Comment by Cerfoglg** [comment]
@VincenzoFerme This issue can be closed, we decided on sending container ID and host ID to identify container data. This has been done in https://github.com/benchflow/data-transformers/issues/37
