### ISSUE TITLE
Use Minio API for Golang

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/collectors#58]
Use Golang APIs for saving files to Minio

https://github.com/minio/minio-go
https://docs.minio.io/docs/golang-client-api-reference

**Comment by VincenzoFerme** [comment]
Closed by https://github.com/benchflow/collectors/pull/70, https://github.com/benchflow/collectors/pull/69, https://github.com/benchflow/collectors/pull/68, https://github.com/benchflow/collectors/pull/72, https://github.com/benchflow/collectors/pull/71, https://github.com/benchflow/collectors/pull/67, and https://github.com/benchflow/collectors/pull/66
